Repository node-fetch/node-fetch, pull requests merged in 2020-05, with the labels that each got.

#779 Improve coverage
  src/request.js
  test/request.js
Labels: enhancement, help wanted

#785 Move to Github Actions
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .travis.yml
  README.md
Labels: enhancement, help wanted

#820 Fix GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  README.md
  package.json
Labels: enhancement

#816 Add feature request issue template
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: good first issue

#815 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: good first issue

#814 Add support issue template
  .github/ISSUE_TEMPLATE/support-or-usage.md
Labels: good first issue

#824 Remove guard for Stream.Readable.destroy
  src/request.js
Labels: enhancement

#810 Breaking: Revamp TypeScript declarations
  .github/workflows/types.yml
  .npmrc
  @types/index.d.ts
  @types/index.test-d.ts
  index.d.ts
  package.json
Labels: enhancement

#834 revamp Headers module
  src/headers.js
  src/index.js
  src/request.js
  test/main.js
Labels: enhancement

#818 Fix default user agent string
  README.md
  src/request.js
Labels: enhancement

#829 Follow xo linter rules more strictly
  README.md
  docs/ERROR-HANDLING.md
  example.js
  package.json
  src/body.js
  src/headers.js
  src/index.js
  src/request.js
  src/utils/get-search.js
  src/utils/is-redirect.js
  src/utils/is.js
  test/main.js
Labels: enhancement

#845 Drop custom Promises and refactor to `async` functions
  README.md
  package.json
  src/body.js
  src/index.js
  test/main.js
Labels: bug, doc, enhancement

#849 Create Code of Conduct
  CODE_OF_CONDUCT.md
Labels: doc, enhancement

#853 Fix Data URI handling and drop all URL analysis RegExps
  package.json
  src/index.js
  src/request.js
  test/external-encoding.js
  test/main.js
Labels: bug, enhancement
