Repository node-fetch/node-fetch, pull requests merged in 2020-06, with the labels that each got.

#843 Polyfill `http.validateHeaderName` and `http.validateHeaderValue`
  .github/workflows/ci.yml
  src/headers.js
Labels: on hold

#846 fix: Correct Node versions were not installed on test matrix
  .github/workflows/ci.yml
  .github/workflows/commonjs.yml
  .github/workflows/lint.yml
  .github/workflows/types.yml
  package.json
  src/index.js
  test/main.js
  test/request.js
Labels: bug, enhancement

#866 [Spec] Should check body _source_ on redirect
  package.json
  src/body.js
  src/index.js
  test/main.js
  test/request.js
  test/response.js
Labels: bug

#842 chore: remove code duplication in custom errors
  src/body.js
  src/errors/abort-error.js
  src/errors/base.js
  src/errors/fetch-error.js
  src/index.js
  src/utils/is.js
  test/main.js
Labels: enhancement

#874 fix: min semver Node version
  .editorconfig
  package.json
Labels: bug

#875 fix window.fetch
  README.md
  package.json
Labels: doc, enhancement

#877 docs(README): remove node-only `timeout` option
  README.md
Labels: doc

#882 chore: remove `string-to-arraybuffer` test dependency
  package.json
  test/main.js
  test/request.js
  test/response.js
Labels: dependencies, enhancement

#880 Allow Mocha tests to be run in parallel
  test/headers.js
  test/main.js
  test/request.js
  test/response.js
  test/utils/server.js
Labels: enhancement

#883 chore: remove `parted` test dependency
  package.json
Labels: dependencies
