Repository node-fetch/node-fetch, pull requests merged in 2022-01, with the labels that each got.

#1105 Don't change relative location header on manual redirect
  README.md
  src/headers.js
  src/index.js
  test/main.js
  test/utils/server.js
Labels: needs-rebase

#903 Handle zero-length OK deflate responses
  src/index.js
  test/server.js
  test/test.js
Labels: enhancement

#1457 test: Update major busboy version
  package.json
  test/utils/server.js
Labels: v3

#1270 ci: semantic-release
  .github/semantic.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  package.json
Labels: enhancement

#1485 chore: completely remove `.buffer()`
  @types/index.test-d.ts
  src/body.js
  test/main.js
  test/request.js
  test/response.js
Labels: v4

#1490 chore: remove EventTarget from the isAbortSignal
  src/utils/is.js
  test/main.js
Labels: v4

#1486 chore: completely remove support for form-data package
  package.json
  src/body.js
  test/main.js
  test/request.js
Labels: v4
